#!/usr/bin/env bash

set -eux -o pipefail

here=$(cd "$(dirname "$0")" && pwd)
tf_output="${here}/tf/quarkdb-cluster/tf-output"

bootstrap_user=$($tf_output -raw bootstrap_user)
bootstrap_password=$($tf_output -raw bootstrap_password)

export SSHPASS=$bootstrap_password

for i in $(seq 0 $(("$( $tf_output num_vms)" - 1))); do
  ip=$($tf_output -json ipv4_addresses | jq --raw-output ".[$i]")
  nixos-anywhere \
    --flake "${here}#quarkdb-${i}" \
    --env-password \
    --generate-hardware-config nixos-generate-config "${here}/hardware-configuration.nix" \
    --target-host "${bootstrap_user}@${ip}"
done
