#!/usr/bin/env bash

set -eux -o pipefail

here=$(cd "$(dirname "$0")" && pwd)
tf_output="${here}/tf-output"
top_dir=$(cd "${here}/.." && pwd)

bootstrap_user=$($tf_output -raw bootstrap_user)
bootstrap_password=$($tf_output -raw bootstrap_password)

export SSHPASS=$bootstrap_password

for vm in $($tf_output -json vms | jq --raw-output 'keys[]'); do
  ip=$($tf_output -json vms | jq --raw-output ".\"$vm\".ipv4_address")
  nixos-anywhere \
    --flake "${top_dir}#${vm}" \
    --env-password \
    --target-host "${bootstrap_user}@${ip}"
done
