#!/usr/bin/env bash

set -eux -o pipefail

here=$(cd "$(dirname "$0")" && pwd)
tf_output="${here}/tf-output"
top_dir=$(cd "${here}/.." && pwd)

for vm in $($tf_output -json vms | jq --raw-output 'keys[]'); do
  ip=$($tf_output -json vms | jq --raw-output ".\"$vm\".ipv4_address")
  nixos-rebuild switch \
    --flake "${top_dir}#${vm}" \
    --target-host "root@${ip}"
done
