#!/usr/bin/env bash

set -eux -o pipefail

top_dir=$(cd "$(dirname "$0")/.." && pwd)
tf_dir=$(cd "${top_dir}/tf/quarkdb-cluster" && pwd)
(cd "$tf_dir" &&
  tofu destroy -var nixos_vars_file="${top_dir}/nixos/nix_vars.json" "$@")
